config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root to: "courses#index"
  resources :enrollments
  resources :students
  resources :sections do
    collection do
      get 'search'
    end
  end
  resources :courses do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Course Management</a>

    <form class="form-inline">
      <div class="btn btn-outline-secondary">
        <%= link_to 'Courses', courses_path, :class => "btn" %>
      </div>
      <div class= "btn btn-outline-secondary">
        <%= link_to 'Sections', sections_path, :class => "btn" %>
      </div>
      <div class= "btn btn-outline-secondary">
        <%= link_to 'Students', students_path, :class => "btn" %>
      </div>
      <div class= "btn btn-outline-secondary">
        <%= link_to 'Log Out', destroy_student_session_path, method: :delete, :class => "btn" %>
      </div>
    </form>


  </nav>


  <body>
    <div class="jumbotron">
    <%= yield %>
    </div>
  </body>

</html>